[project]
name = "oop-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency-injector>=4.46.0",
    "pandas>=2.2.3",
]
